title: Models d'IA
description: Material de suport per a l'assignatura Models d'intel·ligència artificial
theme: just-the-docs

url: https://lawer.github.io/mia/

last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter

exclude:
  - node_modules
  - vendor
  - .bundle
  - scripts
  - apunts/llibre.md
  - _solucionaris
  - apunts/1.-primer_trimestre/3.-Búsqueda en espai d'estats/4.-romania_solucionat.ipynb
  - apunts/1.-primer_trimestre/3.-Búsqueda en espai d'estats/2.-sokoban_solucionat.ipynb
  - apunts/1.-primer_trimestre/3.-Búsqueda en espai d'estats/3.-word_ladder_solucionat.ipynb
  - apunts/1.-primer_trimestre/4.-Búsqueda local i Satisfacció de restriccions/exercicis/1.-exercicis_solucionats.ipynb
  - apunts/1.-primer_trimestre/0.-IA responsable/images/errors-per-idioma.svg
  - apunts/1.-primer_trimestre/0.-IA responsable/guia_docent.md
  - package.json
  - package-lock.json
