title: MIA
description: Material de suport per a l'assignatura Models d'intel·ligència artificial
theme: just-the-docs

url: https://lawer.github.io/mia/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
